import React, { useState } from 'react';
import { Hash, Copy, CheckCircle } from 'lucide-react';
import SEO from '../components/SEO';

const UuidGenerator = () => {
  const [count, setCount] = useState(10);
  const [uuids, setUuids] = useState([]);
  const [copied, setCopied] = useState(false);

  const generateUUIDs = () => {
    const newUuids = [];
    const amount = Math.min(Math.max(1, count), 1000); // limit to 1-1000
    for (let i = 0; i < amount; i++) {
      newUuids.push(crypto.randomUUID());
    }
    setUuids(newUuids);
  };

  const copyToClipboard = async () => {
    if (!uuids.length) return;
    try {
      await navigator.clipboard.writeText(uuids.join('\n'));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  return (
    <div className="container animate-fade-in" style={{ padding: '8rem 1.5rem 4rem', minHeight: '80vh' }}>
      <SEO title="UUID Generator | Iron Claw" description="Instantly generate bulk UUID v4 strings cryptographically secure." />
      
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontFamily: 'var(--font-heading)', color: '#b300ff', fontSize: '2.5rem', marginBottom: '0.5rem', textTransform: 'uppercase' }}>UUID Generator</h1>
        <p style={{ color: 'var(--text-secondary)' }}>Instantly generate bulk v4 UUIDs cryptographically generated by the browser.</p>
      </div>

      <div style={{ display: 'flex', gap: '1rem', marginBottom: '1.5rem', alignItems: 'center', flexWrap: 'wrap' }}>
        <input 
          type="number" 
          value={count} 
          onChange={(e) => setCount(Number(e.target.value))}
          min="1" 
          max="1000"
          style={{ padding: '0.75rem', background: 'rgba(0,0,0,0.6)', border: '1px solid var(--border-color)', color: '#fff', borderRadius: '4px', width: '100px' }}
        />
        <button className="btn btn-primary" onClick={generateUUIDs} style={{ background: '#b300ff', color: '#fff', border: 'none', fontWeight: 'bold' }}>
          Generate UUIDs
        </button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
          <label style={{ color: 'var(--text-muted)', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '1px' }}>Generated UUIDs ({uuids.length})</label>
          <button onClick={copyToClipboard} style={{ background: 'transparent', border: 'none', color: copied ? '#b300ff' : 'var(--text-muted)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.8rem' }}>
            {copied ? <CheckCircle size={14} /> : <Copy size={14} />}
            {copied ? 'Copied All!' : 'Copy All'}
          </button>
        </div>
        <textarea 
          value={uuids.join('\n')}
          readOnly
          placeholder='Click Generate to create UUIDs...'
          style={{ 
            width: '100%', 
            height: '400px', 
            background: 'rgba(179,0,255,0.05)', 
            border: '1px solid var(--border-color)', 
            borderRadius: '0.5rem', 
            padding: '1rem', 
            color: '#b300ff',
            fontFamily: 'monospace',
            fontSize: '14px',
            resize: 'vertical',
            outline: 'none',
            whiteSpace: 'pre'
          }}
        />
      </div>
    </div>
  );
};

export default UuidGenerator;
