import React, { useState } from 'react';
import { Terminal, Code, Lock, Image, Search, ChevronRight, Fingerprint, Link as LinkIcon, Hash, Palette, Type, FileText, Braces, Clock, QrCode, Key, ShieldCheck, SearchCode, Network, Binary, FileLock, TerminalSquare } from 'lucide-react';
import { Link } from 'react-router-dom';
import './GameGrid.css'; // Reuse existing styles for grid layout

const toolsList = [
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    description: 'Format, validate, and beautify massive JSON payloads instantly in the browser.',
    icon: <Code size={24} />,
    color: '#00ff88'
  },
  {
    id: 'base64-encoder',
    title: 'Base64 Decoder',
    description: 'Encode and decode strings and files into Base64 format securely.',
    icon: <Terminal size={24} />,
    color: '#00b3ff'
  },
  {
    id: 'jwt-inspector',
    title: 'JWT Inspector',
    description: 'Decode JSON Web Tokens to securely inspect their payload without sending data.',
    icon: <Lock size={24} />,
    color: '#ff2a2a'
  },
  {
    id: 'css-generator',
    title: 'CSS Generator',
    description: 'Visually generate complex CSS box-shadows, gradients, and border-radius snippets.',
    icon: <Image size={24} />,
    color: '#8d99ae'
  },
  {
    id: 'hash-generator',
    title: 'Hash Generator',
    description: 'Instantly generate secure SHA-256, SHA-512, and SHA-1 hashes directly in your browser.',
    icon: <Fingerprint size={24} />,
    color: '#ff4d4d'
  },
  {
    id: 'url-encoder',
    title: 'URL Encoder',
    description: 'Instantly encode or decode URL query parameters and strings.',
    icon: <LinkIcon size={24} />,
    color: '#ffd700'
  },
  {
    id: 'uuid-generator',
    title: 'UUID Generator',
    description: 'Instantly generate bulk v4 UUIDs cryptographically generated by the browser.',
    icon: <Hash size={24} />,
    color: '#b300ff'
  },
  {
    id: 'color-converter',
    title: 'Color Converter',
    description: 'Instantly convert colors between HEX, RGB, and HSL formats.',
    icon: <Palette size={24} />,
    color: '#00ff88'
  },
  {
    id: 'markdown-previewer',
    title: 'Markdown Previewer',
    description: 'A dual-pane editor to instantly write and preview Markdown.',
    icon: <FileText size={24} />,
    color: '#ff00ff'
  },
  {
    id: 'lorem-ipsum',
    title: 'Lorem Ipsum',
    description: 'Instantly generate placeholder text for mockups and UI designs.',
    icon: <Type size={24} />,
    color: '#ff8a8a'
  },
  {
    id: 'json-to-ts',
    title: 'JSON to TypeScript',
    description: 'Paste a JSON response and instantly generate TypeScript interface definitions.',
    icon: <Braces size={24} />,
    color: '#007acc'
  },
  {
    id: 'cron-generator',
    title: 'Cron Generator',
    description: 'Visually build and generate cron schedule expressions without memorizing syntax.',
    icon: <Clock size={24} />,
    color: '#ffb300'
  },
  {
    id: 'qr-generator',
    title: 'QR Generator',
    description: 'Generate and download high-resolution QR codes instantly in the browser.',
    icon: <QrCode size={24} />,
    color: '#00ffcc'
  },
  {
    id: 'rsa-generator',
    title: 'RSA Keypair',
    description: 'Generate cryptographically secure public and private keypairs using Web Crypto API.',
    icon: <Key size={24} />,
    color: '#ff00ff'
  },
  {
    id: 'bcrypt-generator',
    title: 'Bcrypt Hash',
    description: 'Generate and verify secure bcrypt password hashes using client-side processing.',
    icon: <ShieldCheck size={24} />,
    color: '#00ff88'
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    description: 'Instantly test and visualize JavaScript regular expressions against target strings.',
    icon: <SearchCode size={24} />,
    color: '#ffd700'
  },
  {
    id: 'subnet-calculator',
    title: 'Subnet Calculator',
    description: 'Instantly calculate IPv4 Network, Broadcast, and usable Host ranges.',
    icon: <Network size={24} />,
    color: '#00ffcc'
  },
  {
    id: 'hex-converter',
    title: 'Hex/Binary Converter',
    description: 'Convert ASCII text back and forth to Hexadecimal and Binary representations.',
    icon: <Binary size={24} />,
    color: '#00b3ff'
  },
  {
    id: 'xor-cipher',
    title: 'XOR Cipher',
    description: 'Encrypt and decrypt strings using bitwise XOR operations for malware analysis.',
    icon: <FileLock size={24} />,
    color: '#ff00ff'
  },
  {
    id: 'chmod-calculator',
    title: 'Chmod Calculator',
    description: 'Visually calculate Linux/Unix file permissions and generate the command.',
    icon: <TerminalSquare size={24} />,
    color: '#ffb300'
  }
];

const DevToolsGrid = () => {
  const [searchQuery, setSearchQuery] = useState('');

  const filteredTools = toolsList.filter(tool => 
    tool.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
    tool.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <section className="game-grid-section container" style={{ marginTop: '2rem', marginBottom: '4rem' }}>
      <div className="section-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
        <h2 className="section-title">Essential <span style={{ color: '#00ff88' }}>Utilities</span></h2>
        
        <div className="search-container" style={{ position: 'relative', width: '100%', maxWidth: '300px' }}>
          <Search size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
          <input 
            type="text" 
            className="search-input" 
            placeholder="Search tools..." 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{ 
              width: '100%', 
              padding: '0.75rem 1rem 0.75rem 2.5rem', 
              borderRadius: '2rem', 
              border: '1px solid var(--border-color)', 
              background: 'rgba(0,0,0,0.4)', 
              color: 'var(--text-primary)' 
            }}
          />
        </div>
      </div>

      <div className="game-grid" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))' }}>
        {filteredTools.map((tool) => (
          <div key={tool.id} className="game-card glass-panel" style={{ display: 'flex', flexDirection: 'column', height: '100%', padding: '1.5rem', borderLeft: `4px solid ${tool.color}` }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1rem' }}>
              <div style={{ padding: '0.75rem', background: 'rgba(0,0,0,0.5)', borderRadius: '0.75rem', color: tool.color }}>
                {tool.icon}
              </div>
              <h3 style={{ margin: 0, fontSize: '1.2rem' }}>{tool.title}</h3>
            </div>
            
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', flexGrow: 1, lineHeight: '1.5' }}>
              {tool.description}
            </p>
            
            <Link to={`/tools/${tool.id}`} className="btn" style={{ 
              marginTop: '1.5rem', 
              width: '100%', 
              display: 'flex', 
              justifyContent: 'center', 
              alignItems: 'center', 
              gap: '0.5rem',
              background: 'transparent',
              border: '1px solid var(--border-color)',
              color: 'var(--text-primary)',
              textDecoration: 'none'
            }}>
              Launch Utility <ChevronRight size={16} />
            </Link>
          </div>
        ))}
      </div>
      
      {filteredTools.length === 0 && (
        <div style={{ textAlign: 'center', padding: '4rem', color: 'var(--text-muted)' }}>
          No tools found matching your search.
        </div>
      )}
    </section>
  );
};

export default DevToolsGrid;
